<template>
  <AppFrame active="profile">
    <view class="xr-content profile-page"><view class="profile-heading"><view><view class="xr-page-title">我的与管理设置</view><view class="xr-page-copy">演示环境可切换角色校验前端数据范围与入口。</view></view></view>
      <view class="profile-grid"><view class="xr-card identity-card"><view class="avatar">安</view><view><view class="profile-name">{{ demoStore.user.name }}</view><view class="profile-meta">{{ demoStore.user.department }} · {{ roleNames[demoStore.role] }}</view></view><view class="profile-note">生产版由服务端校验账号、角色、部门与任务归属；照片、位置、AI 密钥不保存在客户端。</view></view>
        <view class="xr-card links-card"><view class="xr-section-title">工作入口</view><view class="setting-row" @click="open('/pages/messages/index')"><text>消息中心</text><text>›</text></view><view v-if="demoStore.can('issue-list')" class="setting-row" @click="open('/pages/issue/list')"><text>整改单</text><text>›</text></view><view v-if="demoStore.can('duty-overview')" class="setting-row" @click="open('/pages/admin/duty')"><text>安全履职总览</text><text>›</text></view><view v-if="demoStore.can('admin')" class="setting-row" @click="open('/pages/admin/inspection')"><text>安监抽查</text><text>›</text></view><view v-if="demoStore.can('admin')" class="setting-row" @click="open('/pages/admin/templates')"><text>检查表模板</text><text>›</text></view></view></view>
      <view class="xr-card roles-card"><view class="roles-heading"><view><view class="xr-section-title">切换演示身份</view><view class="xr-caption">仅用于本地原型核验，不代表生产登录机制。</view></view></view><view class="roles-grid"><view v-for="item in allRoles" :key="item.id" class="role-card" :class="{ active:item.id===demoStore.role }" @click="demoStore.setRole(item.id)"><view><strong>{{ item.roleName }}</strong><text>{{ item.department }} · {{ item.name }}</text></view><text class="role-check">{{ item.id===demoStore.role ? '✓' : '' }}</text></view></view></view>
      <button class="logout" @click="logout">返回登录页</button>
    </view>
  </AppFrame>
</template>
<script setup>
import AppFrame from '../../components/AppFrame.vue'
import { allRoles, demoStore, roleNames } from '../../stores/demo'
function open(url) { uni.navigateTo({ url }) }
function logout() { demoStore.logout(); uni.navigateTo({ url: '/pages/auth/login' }) }
</script>
<style lang="scss" scoped>
.profile-page{max-width:980px}.profile-heading{margin:4rpx 0 20rpx}.profile-grid{display:grid;gap:14rpx}.identity-card,.links-card,.roles-card{padding:22rpx}.identity-card{display:grid;gap:14rpx}.avatar{width:70rpx;height:70rpx;display:flex;align-items:center;justify-content:center;border-radius:12rpx;background:#003c90;color:#fff;font-size:30rpx;font-weight:750}.profile-name{color:#2d3744;font-size:26rpx;font-weight:750}.profile-meta{margin-top:4rpx;color:#7b8794;font-size:19rpx}.profile-note{padding-top:13rpx;border-top:1rpx solid #edf0f3;color:#7b8794;font-size:18rpx;line-height:1.65}.setting-row{display:flex;align-items:center;justify-content:space-between;padding:16rpx 0;border-top:1rpx solid #edf0f3;color:#46515e;font-size:21rpx}.setting-row:first-of-type{margin-top:9rpx}.roles-card{margin-top:15rpx}.roles-grid{display:grid;gap:9rpx;margin-top:14rpx}.role-card{display:flex;align-items:center;justify-content:space-between;padding:13rpx;border:1rpx solid #e4e8ee;border-radius:9rpx}.role-card.active{border-color:#0f52ba;background:#f4f8ff}.role-card strong,.role-card text{display:block}.role-card strong{color:#394452;font-size:20rpx}.role-card text{margin-top:3rpx;color:#84909c;font-size:17rpx}.role-card .role-check{width:27rpx;height:27rpx;margin:0;display:flex;align-items:center;justify-content:center;border-radius:50%;background:#0f52ba;color:#fff}.logout{margin-top:16rpx;background:#eef2f6;color:#495565;border-radius:8rpx;font-size:20rpx}@media(min-width:900px){.profile-heading{margin:0 0 16px}.profile-grid{grid-template-columns:1fr 1.15fr;gap:12px}.identity-card,.links-card,.roles-card{padding:18px}.identity-card{gap:12px}.avatar{width:52px;height:52px;border-radius:9px;font-size:22px}.profile-name{font-size:16px}.profile-meta{font-size:11px}.profile-note{padding-top:10px;font-size:10px}.setting-row{padding:12px 0;font-size:12px}.roles-card{margin-top:14px}.roles-grid{grid-template-columns:repeat(2,1fr);gap:8px;margin-top:11px}.role-card{padding:10px;border-radius:7px}.role-card strong{font-size:11px}.role-card text{font-size:9px}.role-card .role-check{width:20px;height:20px}.logout{margin-top:14px;font-size:11px}}
</style>
