<template><view v-if="task" class="page"><view class="head"><view class="status">{{ dutyStatusText(task.status) }}</view><view class="title">{{ task.actionName }}</view><view class="copy">本周期 {{ task.periodStart }} 至 {{ task.periodEnd }}，截止 {{ task.dueDate }}</view></view><view class="card"><view class="label">履职说明</view><textarea v-model="form.description" :disabled="task.status==='DONE'" placeholder="填写已完成的工作内容、检查范围和发现问题"/><view class="label">现场佐证</view><view class="files"><view v-for="f in form.files" :key="f" class="img"><image :src="f" mode="aspectFill"/></view><view v-if="task.status!=='DONE'" class="upload" @click="choose">＋<text>照片</text></view></view><view v-if="task.status==='DONE'" class="readonly">本周期已提交，历史记录只读保留，不允许删除或覆盖。</view></view><button v-if="task.status!=='DONE'" class="submit" :disabled="!form.description" @click="save">提交本周期履职记录</button></view></template>
<script setup>
import { computed, reactive } from 'vue'
import { onLoad } from '@dcloudio/uni-app'
import { chooseEvidenceImages } from '../../services/platform'
import { dutyStatusText, listMyDuties, submitDuty } from '../../services/duty'
let id=''; const source=reactive({items:[]}); const task=computed(()=>source.items.find(x=>x.id===id));const form=reactive({description:'',files:[]})
onLoad(async(o)=>{id=o.id;source.items=await listMyDuties({});const item=task.value;if(item){form.description=item.description;form.files=item.files||[]}})
async function choose(){try{const r=await chooseEvidenceImages();form.files.push(...r.tempFilePaths)}catch{}} async function save(){await submitDuty(id,form);uni.showToast({title:'已记录本周期履职',icon:'success'});setTimeout(()=>uni.navigateBack(),500)}
</script>
<style lang="scss" scoped>.page{padding:28rpx}.head,.card{background:#fff;border:1rpx solid #e0e8e3;border-radius:22rpx;padding:28rpx}.card{margin-top:18rpx}.status{display:inline-block;color:#006e55;background:#e7f2ed;padding:6rpx 12rpx;border-radius:7rpx;font-size:22rpx}.title{font-size:35rpx;font-weight:700;margin:18rpx 0 8rpx}.copy,.readonly{font-size:22rpx;color:#718078;line-height:1.6}.label{font-size:26rpx;font-weight:650;margin:8rpx 0 14rpx}.label:not(:first-child){margin-top:30rpx}textarea{box-sizing:border-box;width:100%;height:150rpx;background:#f5f8f6;border-radius:14rpx;padding:18rpx;font-size:25rpx}.files{display:flex;gap:14rpx;flex-wrap:wrap}.img,.upload{height:116rpx;width:116rpx;border-radius:14rpx;overflow:hidden}.img image{height:100%;width:100%}.upload{border:1rpx dashed #91a29a;color:#006e55;display:flex;flex-direction:column;justify-content:center;align-items:center;font-size:40rpx}.upload text{font-size:20rpx}.readonly{margin-top:20rpx;background:#f1f5f3;padding:18rpx;border-radius:12rpx}.submit{height:92rpx;line-height:92rpx;background:#006e55;color:#fff;border-radius:16rpx;margin-top:22rpx;font-size:28rpx}.submit[disabled]{background:#b5c2bd}</style>
