<template>
  <AppFrame active="duty"><view v-if="task" class="xr-content record-page"><view class="record-heading"><view><view class="xr-status" :class="statusClass(task.status)">{{ dutyStatusText(task.status) }}</view><view class="xr-page-title">{{ task.actionName }}</view><view class="xr-page-copy">周期 {{ task.periodStart }} 至 {{ task.periodEnd }}，截止 {{ task.dueDate }}</view></view></view><view class="xr-card record-card"><view class="field"><text class="xr-field-label">履职说明</text><textarea v-model="form.description" class="xr-textarea" :disabled="task.status==='DONE'" placeholder="填写工作内容、检查范围和发现问题"/></view><view class="field"><text class="xr-field-label">现场佐证</text><view class="record-files"><view v-for="file in form.files" :key="file" class="record-image"><image :src="file" mode="aspectFill"/></view><view v-if="task.status!=='DONE'" class="record-image add" @click="choose">＋<text>上传图片</text></view></view></view><view v-if="task.status==='DONE'" class="record-readonly">本周期已提交，历史记录仅供查看，不允许删除或覆盖。</view><button v-else class="xr-btn xr-btn-primary record-submit" :disabled="!form.description" @click="save">提交本周期记录</button></view></view><view v-else class="xr-content xr-empty">未找到履职任务</view></AppFrame>
</template>
<script setup>
import { computed, reactive } from 'vue'
import { onLoad } from '@dcloudio/uni-app'
import AppFrame from '../../components/AppFrame.vue'
import { chooseEvidenceImages } from '../../services/platform'
import { dutyStatusText, listMyDuties, submitDuty } from '../../services/duty'
let id='';const source=reactive({items:[]}),task=computed(()=>source.items.find((item)=>item.id===id)),form=reactive({description:'',files:[]});onLoad(async(options)=>{id=options.id;source.items=await listMyDuties({});const item=task.value;if(item){form.description=item.description;form.files=item.files||[]}});async function choose(){try{const result=await chooseEvidenceImages();form.files.push(...result.tempFilePaths)}catch{}}async function save(){await submitDuty(id,form);uni.showToast({title:'履职记录已提交',icon:'success'});setTimeout(()=>uni.navigateBack(),450)}function statusClass(value){return ({PENDING:'xr-status-warning',OVERDUE:'xr-status-major',DONE:'xr-status-review'})[value]||'xr-status-muted'}
</script>
<style lang="scss" scoped>
.record-page{max-width:780px}.record-heading{margin:4rpx 0 20rpx}.record-heading .xr-page-title{margin-top:12rpx}.record-card{padding:22rpx}.field{margin-top:19rpx}.field:first-child{margin-top:0}.record-files{display:flex;flex-wrap:wrap;gap:11rpx}.record-image{width:106rpx;height:106rpx;overflow:hidden;border-radius:8rpx;background:#eef2f5}.record-image image{width:100%;height:100%}.record-image.add{display:flex;flex-direction:column;align-items:center;justify-content:center;border:1rpx dashed #aeb9c7;color:#718094;font-size:31rpx}.record-image.add text{font-size:17rpx}.record-readonly{margin-top:20rpx;padding:13rpx;border-radius:8rpx;background:#f5f7fa;color:#718094;font-size:19rpx;line-height:1.6}.record-submit{width:100%;margin-top:22rpx}@media(min-width:900px){.record-heading{margin:0 0 16px}.record-heading .xr-page-title{margin-top:9px}.record-card{padding:20px}.field{margin-top:16px}.record-files{gap:8px}.record-image{width:72px;height:72px}.record-image.add{font-size:22px}.record-image.add text{font-size:9px}.record-readonly{margin-top:16px;padding:10px;font-size:11px}.record-submit{margin-top:18px}}
</style>
