<template>
  <DesktopSidebar active="issues"/><view class="page xr-desktop-page"><view class="head"><view><view class="eyebrow">受限协作区</view><view class="title">整改单</view><view class="copy">仅安监部可全量处理；市场部仅查看本部门交办事项。</view></view><button v-if="demoStore.can('issue-assign')" class="create" @click="create">新建交办</button></view>
    <view v-if="!allowed" class="denied"><view class="denied-title">无整改单处理权限</view><view>普通员工可使用随手拍和我的履职。已公开事项可在待办中查看进度。</view><button @click="back">返回待办</button></view>
    <template v-else><view class="filters"><view v-for="x in filters" :key="x.value" class="filter" :class="{active:status===x.value}" @click="status=x.value">{{x.label}}</view></view><view v-for="issue in rows" :key="issue.id" class="row" :class="{major:issue.major}" @click="open(issue.id)"><view class="top"><view class="status" :class="statusClass(issue.status)">{{issue.status}}</view><view v-if="issue.major" class="major">重大隐患</view><view class="id">{{issue.id}}</view></view><view class="name">{{issue.title}}</view><view class="meta"><text>{{issue.assignee || '待安监交办'}}</text><text>限期 {{issue.deadline}}</text></view></view><view v-if="!rows.length" class="empty">当前筛选没有整改单</view></template>
  </view>
</template>
<script setup>
import {computed,ref} from 'vue'
import {demoStore} from '../../stores/demo'
import DesktopSidebar from '../../components/DesktopSidebar.vue'
const status=ref('');const allowed=computed(()=>demoStore.can('issue-list'));const filters=[{label:'全部',value:''},{label:'待交办',value:'待交办'},{label:'待整改',value:'待整改'},{label:'待复核',value:'待复核'},{label:'已逾期',value:'已逾期'}];const rows=computed(()=>demoStore.visibleIssues().filter(x=>!status.value||x.status===status.value));function statusClass(v){return ({'待交办':'draft','待整改':'todo','待复核':'review','已逾期':'overdue','已闭环':'closed'})[v]}function open(id){uni.navigateTo({url:`/pages/issue/detail?id=${id}`})}function create(){uni.navigateTo({url:'/pages/issue/create'})}function back(){uni.switchTab({url:'/pages/index/index'})}
</script>
<style lang="scss" scoped>
.page{padding:32rpx 28rpx 64rpx;max-width:1240px;margin:auto}.head{display:flex;justify-content:space-between;align-items:flex-end;gap:20rpx;margin:12rpx 0 28rpx}.eyebrow{font-size:20rpx;letter-spacing:3rpx;color:#9f2349}.title{font-size:44rpx;font-weight:750}.copy,.meta{font-size:22rpx;color:#756c6b;line-height:1.55}.create{margin:0;background:#211d1d;color:#fff;border-radius:12rpx;font-size:23rpx}.filters{white-space:nowrap;overflow:auto;padding-bottom:16rpx}.filter{display:inline-block;padding:11rpx 18rpx;background:#eee8e5;color:#756c6b;margin-right:12rpx;border-radius:10rpx;font-size:22rpx}.filter.active{background:#9f2349;color:#fff}.row{position:relative;background:#fffcfa;border-bottom:1rpx solid #e8dfdc;padding:24rpx;margin-bottom:10rpx}.row.major{box-shadow:inset 7rpx 0 #c53a34}.top,.meta{display:flex;align-items:center;gap:12rpx}.status,.major{font-size:20rpx;padding:5rpx 10rpx;border-radius:7rpx}.draft{background:#ede8e5;color:#655e5b}.todo{background:#fff0e5;color:#995413}.review{background:#edf1fb;color:#3d5b99}.overdue{background:#fff0ee;color:#b62e2b}.closed{background:#edf5ef;color:#287144}.major{background:#f8e8ed;color:#9f2349}.id{margin-left:auto;color:#9d9390;font-size:19rpx}.name{font-size:30rpx;font-weight:680;margin:18rpx 0 12rpx}.meta{justify-content:space-between}.denied{background:#fffcfa;border:1rpx solid #e8dfdc;padding:46rpx 30rpx;text-align:center;border-radius:20rpx;color:#756c6b;line-height:1.7}.denied-title{font-size:31rpx;font-weight:700;color:#211d1d}.denied button{margin-top:22rpx;background:#211d1d;color:#fff;border-radius:12rpx;font-size:25rpx}.empty{text-align:center;color:#8f8582;padding:100rpx 0}
</style>
