<template>
  <AppFrame active="issues">
    <view class="xr-content review-page"><view v-if="issue && allowed" class="review-wrap"><view class="review-heading"><view><view class="xr-page-title">复核闭环</view><view class="xr-page-copy">确认整改佐证是否满足闭环要求。</view></view><view class="xr-status xr-status-review">待复核</view></view><view class="review-grid"><view class="xr-card original-card"><view class="xr-section-title">原始隐患</view><view class="original-copy">{{ issue.description }}</view><view class="review-facts"><view><text>上报人员</text><strong>{{ issue.reporter }}</strong></view><view><text>上报时间</text><strong>{{ issue.createdAt }}</strong></view><view><text>现场位置</text><strong>{{ issue.location || '未标注' }}</strong></view><view><text>责任部门</text><strong>{{ issue.assigneeDept }}</strong></view></view><view class="review-photo"><image v-if="issue.attachments&&issue.attachments.length" :src="issue.attachments[0]" mode="aspectFill"/><view v-else>等待原始现场图片</view></view></view><view class="xr-card remediation-card"><view class="evidence-header"><view><view class="xr-section-title">整改佐证</view><view class="xr-caption">市场营销部提交的材料</view></view><view class="xr-status xr-status-review">待复核</view></view><view class="remediation-copy">{{ issue.rectification ? issue.rectification.note : '尚未提交整改材料。' }}</view><view class="remediation-meta">提交时间 {{ issue.rectification ? issue.rectification.submittedAt : '-' }}</view><view class="review-photos"><view v-for="file in evidenceFiles" :key="file" class="review-thumb"><image :src="file" mode="aspectFill"/></view><view v-if="!evidenceFiles.length" class="review-thumb empty-thumb">无图片</view></view><view class="field"><text class="xr-field-label">闭环意见</text><textarea v-model="reviewNote" class="xr-textarea" placeholder="填写复核意见，退回整改时请明确原因"/></view><view class="review-buttons"><button class="xr-btn xr-btn-danger" @click="returnIssue">退回整改</button><button class="xr-btn xr-btn-primary" @click="close">确认闭环</button></view></view></view></view><view v-else-if="issue" class="xr-empty">无复核权限，已返回可访问范围。</view><view v-else class="xr-empty">未找到待复核隐患</view></view>
  </AppFrame>
</template>
<script setup>
import { computed, ref } from 'vue'
import { onLoad } from '@dcloudio/uni-app'
import AppFrame from '../../components/AppFrame.vue'
import { demoStore } from '../../stores/demo'
let id = ''
const issue = computed(() => demoStore.issues.find((item) => item.id === id))
const allowed = computed(() => demoStore.can('issue-review', issue.value))
const reviewNote = ref('')
const evidenceFiles = computed(() => issue.value?.rectification?.attachments || [])
onLoad((options) => { id = options.id })
function back() { uni.navigateBack({ delta: 1, fail: () => uni.switchTab({ url: '/pages/index/index' }) }) }
function returnIssue() { if (!allowed.value || !reviewNote.value) { uni.showToast({ title: '请填写退回原因', icon: 'none' }); return }; demoStore.returnIssue(id, reviewNote.value); uni.showToast({ title: '已退回整改', icon: 'success' }); setTimeout(back, 450) }
function close() { if (!allowed.value) return; demoStore.closeIssue(id, reviewNote.value || undefined); uni.showToast({ title: '已确认闭环', icon: 'success' }); setTimeout(back, 450) }
</script>
<style lang="scss" scoped>
.review-page{max-width:1040px}.review-heading{display:flex;justify-content:space-between;align-items:flex-start;margin:4rpx 0 20rpx}.review-grid{display:grid;gap:16rpx}.original-card,.remediation-card{padding:22rpx}.original-copy{margin-top:15rpx;color:#46505d;font-size:21rpx;line-height:1.65}.review-facts{display:grid;grid-template-columns:repeat(2,1fr);gap:9rpx;margin-top:17rpx}.review-facts view{padding:11rpx;border-radius:7rpx;background:#f5f7fa}.review-facts text,.review-facts strong{display:block}.review-facts text{color:#84909e;font-size:17rpx}.review-facts strong{margin-top:4rpx;color:#3c4754;font-size:19rpx;line-height:1.35}.review-photo{height:190rpx;margin-top:15rpx;display:flex;align-items:center;justify-content:center;overflow:hidden;border-radius:8rpx;background:#eef2f5;color:#7c8795;font-size:19rpx}.review-photo image{width:100%;height:100%}.evidence-header{display:flex;align-items:flex-start;justify-content:space-between;gap:12rpx}.remediation-copy{margin-top:17rpx;padding:13rpx;border-radius:8rpx;background:#f5f7fa;color:#46505d;font-size:20rpx;line-height:1.6}.remediation-meta{margin-top:8rpx;color:#7f8996;font-size:18rpx}.review-photos{display:flex;gap:9rpx;flex-wrap:wrap;margin-top:14rpx}.review-thumb{width:84rpx;height:84rpx;overflow:hidden;border-radius:7rpx;background:#eef2f5}.review-thumb image{width:100%;height:100%}.empty-thumb{display:flex;align-items:center;justify-content:center;color:#8b95a2;font-size:17rpx}.review-buttons{display:flex;justify-content:flex-end;gap:12rpx;margin-top:20rpx}@media(min-width:900px){.review-heading{margin:0 0 16px}.review-grid{grid-template-columns:1fr 1fr;gap:14px}.original-card,.remediation-card{padding:18px}.original-copy{margin-top:12px;font-size:12px}.review-facts{gap:7px;margin-top:13px}.review-facts view{padding:9px}.review-facts text{font-size:9px}.review-facts strong{margin-top:3px;font-size:11px}.review-photo{height:150px;margin-top:13px;font-size:10px}.remediation-copy{margin-top:13px;padding:10px;font-size:11px}.remediation-meta{margin-top:6px;font-size:10px}.review-photos{gap:7px;margin-top:11px}.review-thumb{width:62px;height:62px}.empty-thumb{font-size:9px}.review-buttons{gap:8px;margin-top:16px}}
</style>
